### ISSUE TITLE
In and Out mismatch

### ISSUE THREAD

**Issue by sneiderlein** [floooh/sokol-tools#71] opened 2022-05-01 16:46 UTC
Hi,

I can't seem to be able to build a project that worked ok recently using fips. The error is coming from sokol-shdc:

`C:/dev/fips/churchton-2/src/shapes-sapp.glsl(230): error : outputs of vs 'shapes_vs' don't match inputs of fs 'shapes_fs' for attr #0 (vs=fragment_color,fs=) 
[C:\dev\fips\fips-build\churchton-2\win64-vscode-debug\src\ALL_GENERATE.vcxproj]`

The outputs in the vshader look like this:
`out vec4 fragment_color;
out vec3 fragment_position;
out vec3 fragment_normal;
out vec2 fragment_uv;
out mat3 TBN;`

The inputs on the fshader look like this:
`in vec4 fragment_color;
in vec3 fragment_position;
in vec3 fragment_normal;
in vec2 fragment_uv;
in mat3 TBN;`

The code was building perfectly several months ago, now from a new laptop, I can't seem to be able to do it.

**Comment by floooh** [comment] 2022-05-02 09:29
The SPIRVTools optimizer passes had become more aggressive about removing unused input/output items in a somewhat recent update, but I though I had fixed this with this commit:

https://github.com/floooh/sokol-tools/commit/16492a01b47657e62088df5a9c8b5b5fd47b0e25

Can you post the shader for investigation? Worst case is that you need to fix the shader so that the fragment shader doesn't have any inputs which are not used by the shader code, and the vertex shader doesn't have any outputs that the fragment shader doesn't expect.

**Comment by sneiderlein** [comment] 2022-05-04 09:40
Sure, here is the shader:
https://pastebin.com/DF69WTvP

It's really ugly :)
I had to do this workaround with the lights, because the compiler was crashing when I tried to use arrays or any types other than floating point values as uniforms. I'll try to remove unused stuff when I get around to it.

Thank you for a fast reply :)

**Comment by floooh** [comment] 2022-05-06 15:42
The error is most likely caused by ```fragment_color```, because this isn't used in the fragment shader (the line is commented out).
But it's strange that this is an issue with my recent fix I mentioned above. I'll have a look...

**Comment by floooh** [comment] 2022-05-06 15:48
Hmm, I'm actually able to compile that shader with the latest version committed to https://github.com/floooh/sokol-tools-bin:

```
~/projects/sokol-tools-bin/bin/osx_arm64/sokol-shdc -i bla.glsl -o bla.glsl.h -l hlsl4:metal_macos:glsl330
```

...and if I **manually** remove the line ```in vec4 fragment_color;```, I get the error:

```
bla.glsl:230:0: error: outputs of vs 'shapes_vs' don't match inputs of fs 'shapes_fs' for attr #0 (vs=fragment_color,fs=fragment_position)
```

...both results are expected.

Can you check that you're indeed using the latest executables?

**Comment by floooh** [comment] 2022-05-06 16:35
PS: just a heads up, there's a new sokol-shdc update related to a different issue (https://github.com/floooh/sokol-tools/issues/72), just so you're not confused if you think you are on the latest binaries, but still get new ones :)

**Closed** 2022-07-11 15:25 UTC
