### ISSUE TITLE
multiple "layout(binding=0) uniform sampler2D" assigns incorrect slots on metal / macOS

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#29] opened 2020-01-14 12:07 UTC
The binding assignment isn't used correctly on metal. The defined SLOT_xxx variables are set correctly, but in the actual metal code the samplers are assigned slots in the order they appear in the shader code.

Managed to replicate the issue by changing the texcube-sapp.glsl example fragment shader to the following: 
```
#pragma sokol @fs fs
layout(binding=0) uniform sampler2D tex1;     // < --- note 'wrong' order here
layout(binding=1) uniform sampler2D tex0;

in vec4 color;
in vec2 uv;
out vec4 frag_color;

void main() {
    vec4 color0 = texture(tex0, uv);    // <--- 'right' order usage here
    vec4 color1 = texture(tex1, uv);
    frag_color = (color0 + color1) * color;
}
#pragma sokol @end
```

After compilation the metal shader code generated looks like this:
(texcube-sapp.glsl.h)
```
#define SLOT_tex0 (1)
#define SLOT_tex1 (0)

...

    #line 13 ""
    fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex0 [[texture(0)]], texture2d<float> tex1 [[texture(1)]], sampler tex0Smplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]])
    {
        main0_out out = {};
    #line 13 ""
    #line 14 ""
        out.frag_color = (tex0.sample(tex0Smplr, in.uv) + tex1.sample(tex1Smplr, in.uv)) * in.color;
        return out;
    }
```

You can see that tex0 is assigned texture(0) and tex1 is assigned texture(1).

It works correctly on Windows/DirectX, have not tested other platforms.

**Comment by mattiasljungstrom** [comment] 2020-01-14 14:25
This issue might be related: https://github.com/KhronosGroup/SPIRV-Cross/issues/1248

**Comment by mattiasljungstrom** [comment] 2020-01-14 15:43
When I rebuild sokol-shdc from scratch with latest ext dependencies, it seems to generate correct code. Maybe you only need to trigger a rebuild of sokol-tools-bin?

**Comment by floooh** [comment] 2020-01-14 16:28
Thanks for digging into this, I'll try updating the dependencies and trigger a build!

**Comment by floooh** [comment] 2020-01-14 17:09
Ok, I have updated the SPIRVCross dependency (but not the others), and updates the exes in sokol-tools-bin. If something's wrong, just reopen this ticket :)

**Comment by mattiasljungstrom** [comment] 2020-01-14 17:23
Looks like it's still not working with the binaries. When I rebuilt the tool I did a: git submodules update --recursive, and then I had to clean out the old fips-build files to get it to compile.

**Comment by floooh** [comment] 2020-01-14 18:04
Hmm ok, then it must be one of the other dependencies, strange though. I'll try another attempt tomorrow evening.

**Comment by floooh** [comment] 2020-01-14 18:14
Hmm I'm getting compiler errors in SPIRV-Tools because of their stupid use of generated files:

```
SPIRV-Tools/source/ext_inst.cpp:31:10: fatal error: 'opencl.debuginfo.100.insts.inc' file not found
```
I'll try to look into it tomorrow or so...

**Comment by mattiasljungstrom** [comment] 2020-01-14 19:37
yeah, I had something similar. Think you need to delete any old fips-build or other generated folders.

**Comment by floooh** [comment] 2020-01-15 12:55
Ok, I've started to look a bit deeper into the issue (I can reproduce it with your example shader), and the code where SPIRVCross builds those function argument lists looks a bit weird to me. Each "thing" in SPIRVCross (uniform and local variables, arguments, etc...) carries 'decorators' with it, for instance, (location=X) or (binding=Y) are different decorators carried with uniform variables, and I would expect SPIRVCross to use one of those for the Metal resource bind slot, instead it uses another decorator "index", which seems to be the order this type of resource shows up in the source file, this is the relevant line (buffers work the same).

This is the code in question which builds the ```[[texture(N)]]``` string, note the ```r.index```:

https://github.com/KhronosGroup/SPIRV-Cross/blob/172e39f0398b920cfc221b7826c92105d44ad647/spirv_msl.cpp#L9457

I haven't seen any code which somehow sets this ```r.index``` from the location or binding.

And I'm wondering why it would work with updating the sokol-shdc dependencies. It might be that SPIRVTools or glslangValidator changed behaviour and sorts the uniforms by the location and/or binding decorator, so that it works "by accident".

I'll ask around on the SPIRVCross issue tracker. In the meantime I think I can "patch" this index decorator by copying either the location or binding decoration into it, this seems to be a more robust solution.

**Comment by floooh** [comment] 2020-01-15 13:08
Ah ok, better solution: it seems like setting the ```enable_decoration_binding``` option in the CompilerMSL class fixes the problem, this seems to copy the binding decorator into the index decorator (basically the same thing I was going to do manually).

The fragment function from your example shader looks this this after this change:

```cpp
    fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex1 [[texture(0)]], texture2d<float> tex0 [[tex
ture(1)]], sampler tex1Smplr [[sampler(0)]], sampler tex0Smplr [[sampler(1)]])
    {
        main0_out out = {};
    #line 13 ""
    #line 14 ""
        out.frag_color = (tex0.sample(tex0Smplr, in.uv) + tex1.sample(tex1Smplr, in.uv)) * in.color;
        return out;
    }
```

I'll test this change with the sokol samples and emulator stuff, and if everything works I'll update the exes (in the evening).

**Comment by mattiasljungstrom** [comment] 2020-01-15 13:47
Sounds good! It might well be that the updated code is correct by chance. The enable_decoration_binding setting seems to be the right way to do it. 

They mention it in the issue I linked above as well: "MSL binding space does not match SPIR-V, and MSL binding space is allocated on-demand. There is the option https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L303, or --msl-decoration-binding from CLI which will map DecorationBinding to MSL binding space. It won't work in the general case however, but for simple cases like this, it should do the trick.

**Comment by floooh** [comment] 2020-01-15 17:44
fix is committed, executables are on the way...

**Closed** 2020-01-15 17:44 UTC

**Comment by floooh** [comment] 2020-01-15 18:10
ok, exes are committed, please give it a shot :)

**Comment by mattiasljungstrom** [comment] 2020-01-15 18:33
Working as expected now. Thanks!
